import type {PanoPostData} from "./components/pano";

// Static fixture: the landing page isn't wired to the live `posts(...)` query yet.
// (The /pano feed itself does read live over fate via PanoFeed.)
export const POSTS: PanoPostData[] = [
	{
		id: "p1",
		rank: 1,
		title: "türkiye'de kendi web yığınını çalıştırmak: nginx + caddy notları",
		href: "#",
		url: "https://github.com/edak/notes",
		host: "github.com",
		tags: [{kind: "show", label: "göster"}],
		author: "eda_k",
		agoLabel: "3 saat önce",
		commentCount: 14,
		score: 47,
		myVote: true,
	},
	{
		id: "p2",
		rank: 2,
		title: 'küçük bir forum yazılımı için "yeterince iyi" oran sınırlama',
		href: "#",
		host: "kampus.dev",
		tags: [
			{kind: "discuss", label: "tartışma"},
			{kind: "ask", label: "soru"},
		],
		author: "mert",
		agoLabel: "5 saat önce",
		commentCount: 28,
		score: 63,
	},
	{
		id: "p3",
		rank: 3,
		title: "oyun motoru yazıyorum ama wgpu nasıl debug ediliyor cidden bilen var mı",
		href: "#",
		tags: [{kind: "rant", label: "söylenme"}],
		author: "arda",
		agoLabel: "7 saat önce",
		commentCount: 9,
		score: 21,
	},
	{
		id: "p4",
		rank: 4,
		title: "CSS'de container queries'ten sonra dünya değişti mi",
		href: "#",
		host: "css-tricks.com",
		tags: [{kind: "discuss", label: "tartışma"}],
		author: "selin",
		agoLabel: "12 saat önce",
		commentCount: 41,
		score: 88,
	},
	{
		id: "p5",
		rank: 5,
		title: "neden hala IRC kullanıyorum",
		href: "#",
		tags: [{kind: "meta", label: "meta"}],
		author: "kerem",
		agoLabel: "1 gün önce",
		commentCount: 17,
		score: 34,
	},
];

// Static fixture: replaced with a live fate query once the landing page is wired through.
export const LANDING_TERMS = [
	{
		slug: "race-condition",
		title: "race condition",
		count: 17,
		gloss: "yarış halinde erişimden doğan belirsizlik",
		author: "umutsirin",
		agoLabel: "2 gün",
	},
	{
		slug: "onbellek",
		title: "önbellek",
		count: 12,
		gloss: "hesaplanmış olanı saklama tekniği",
		author: "arthur",
		agoLabel: "3 gün",
	},
	{
		slug: "yatay-olcekleme",
		title: "yatay ölçekleme",
		count: 9,
		gloss: "sunucu eklemekle olan",
		author: "elif",
		agoLabel: "4 gün",
	},
	{
		slug: "crdt",
		title: "CRDT",
		count: 8,
		gloss: "çatışmasız çoğaltılan veri tipi",
		author: "meriç",
		agoLabel: "5 gün",
	},
	{
		slug: "kimlik-dogrulama",
		title: "kimlik doğrulama",
		count: 6,
		gloss: '"sen kimsin" sorusu',
		author: "canyilmaz",
		agoLabel: "6 gün",
	},
];
