/**
 * `roadmap diagram` pure core — generate the GitHub-native mermaid dependency diagram from
 * ROADMAP.md's `## Arcs` / `## Campaigns` tables plus the `## Dependencies` declaration. Every
 * arc and campaign becomes a node styled by its lifecycle state (active / queued / done); every
 * `## Dependencies` row becomes one directed `blocker --> blocks` edge. An endpoint that names an
 * arc/campaign (by name) binds to that node; any other endpoint — an issue `#N`, an `ADR NNNN`,
 * or a not-yet-tabled arc — renders as an `external` node so a real cross-item dependency can be
 * drawn even when one end is not (yet) a roadmap row.
 *
 * IO-free and DETERMINISTIC: same tables in ⇒ byte-identical block out. That is the load-bearing
 * property — the committed block in ROADMAP.md is this function's output, and the follow-up
 * roadmap-guard drift check regenerates and compares against it (#3870). Node order is fixed:
 * arcs in table order, then campaigns in table order, then external endpoints in first-appearance
 * order across the dependency rows; edges are in dependency-table order. Nothing depends on map
 * iteration order or live GitHub state. The ROADMAP.md read lives in `command.ts`.
 */
import {parseSectionRows, type RoadmapRow} from "../roadmap-guard/roadmap-guard.ts";

/** One declared dependency edge: `blocker` must land before `blocks` can proceed. */
export interface Dependency {
	readonly blocker: string;
	readonly blocks: string;
	readonly why: string;
}

/**
 * Parse the `## Dependencies` declaration table (`Blocker | Blocks | Why`) into edges, reusing
 * roadmap-guard's table tokenizer so the diagram and any guard read the grammar identically.
 * Rows missing an endpoint are dropped (a stray table artifact), never turned into a phantom edge.
 */
export const parseDependencies = (md: string): ReadonlyArray<Dependency> =>
	parseSectionRows(md, "Dependencies")
		.map((cells) => ({
			blocker: (cells[0] ?? "").trim(),
			blocks: (cells[1] ?? "").trim(),
			why: (cells[2] ?? "").trim(),
		}))
		.filter((d) => d.blocker !== "" && d.blocks !== "");

/** A mermaid node's style class — an arc/campaign lifecycle state, or `external` for a non-row endpoint. */
type NodeStyle = "active" | "queued" | "done" | "external";

/** Lowercase-and-underscore a name into a mermaid-safe node id fragment (collapsing runs, trimming edges). */
const slug = (s: string): string =>
	s
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "_")
		.replace(/^_+|_+$/g, "");

/** A row's lifecycle state mapped to its node style; an unrecognized state (guard-rejected) defaults to queued. */
const styleOf = (state: string): NodeStyle =>
	state === "active" ? "active" : state === "done" ? "done" : "queued";

/** Normalize a name for endpoint↔row matching — trimmed, case-insensitive. */
const norm = (s: string): string => s.trim().toLowerCase();

const TAB = "\t";

/**
 * Generate the fenced ```mermaid block (including its fences) from the parsed tables + declared
 * dependencies. Pure and total; the returned string carries no trailing newline (the command adds
 * one via `Console.log`), so the committed ROADMAP.md block is exactly this output.
 */
export const generateDiagram = (
	arcs: ReadonlyArray<RoadmapRow>,
	campaigns: ReadonlyArray<RoadmapRow>,
	deps: ReadonlyArray<Dependency>,
): string => {
	const arcNodes = arcs.map((r) => ({
		id: `arc_${slug(r.name)}`,
		label: r.name,
		style: styleOf(r.state),
	}));
	const campNodes = campaigns.map((r) => ({
		id: `camp_${slug(r.name)}`,
		label: r.name,
		style: styleOf(r.state),
	}));

	// Canonical name → id for arc/campaign rows: a dependency endpoint naming a row binds to it.
	const byName = new Map<string, string>();
	for (const n of [...arcNodes, ...campNodes]) {
		const key = norm(n.label);
		if (!byName.has(key)) byName.set(key, n.id);
	}

	// Resolve each endpoint to a node id, collecting non-row endpoints as external nodes in
	// first-appearance order across the (blocker, blocks) reads — the determinism contract.
	const externals: Array<{id: string; label: string}> = [];
	const seenExt = new Set<string>();
	const resolve = (endpoint: string): string => {
		const hit = byName.get(norm(endpoint));
		if (hit !== undefined) return hit;
		const id = `ext_${slug(endpoint)}`;
		if (!seenExt.has(id)) {
			seenExt.add(id);
			externals.push({id, label: endpoint});
		}
		return id;
	};
	const edges = deps.map((d) => ({from: resolve(d.blocker), to: resolve(d.blocks)}));

	const lines: Array<string> = [];
	lines.push("```mermaid");
	lines.push("%% GENERATED by `pipeline-cli roadmap diagram` — do not hand-edit; regenerate.");
	lines.push(
		"%% Nodes = every ## Arcs / ## Campaigns row (styled by state); edges = ## Dependencies rows (#3870).",
	);
	lines.push("flowchart TD");
	lines.push(`${TAB}subgraph arcs["Arcs"]`);
	for (const n of arcNodes) lines.push(`${TAB}${TAB}${n.id}["${n.label}"]:::${n.style}`);
	lines.push(`${TAB}end`);
	lines.push(`${TAB}subgraph campaigns["Campaigns"]`);
	for (const n of campNodes) lines.push(`${TAB}${TAB}${n.id}["${n.label}"]:::${n.style}`);
	lines.push(`${TAB}end`);
	for (const e of externals) lines.push(`${TAB}${e.id}["${e.label}"]:::external`);
	for (const e of edges) lines.push(`${TAB}${e.from} --> ${e.to}`);
	lines.push(`${TAB}classDef active fill:#1a7f37,stroke:#116329,color:#ffffff;`);
	lines.push(`${TAB}classDef queued fill:#9a6700,stroke:#7d4e00,color:#ffffff;`);
	lines.push(`${TAB}classDef done fill:#57606a,stroke:#424a53,color:#ffffff;`);
	lines.push(
		`${TAB}classDef external fill:#ddf4ff,stroke:#54aeff,color:#0550ae,stroke-dasharray:5 5;`,
	);
	lines.push("```");
	return lines.join("\n");
};
