export const spectatorStyles = `
.hsbg-spectator{--surface:#171512;--surface-sunken:#100f0d;--surface-raised:#24201a;--border:#5c5140;--border-faint:#37312a;--border-strong:#9d8458;--text-primary:#f1e7d5;--text-secondary:#d2c3ac;--text-muted:#baad98;--accent:#d3af6c;--accent-fg:#17120b;--accent-soft:#463722;--accent-faint:#292218;--link:#e7c78e;--focus-ring:2px solid var(--accent);--focus-ring-offset:2px;--hsbg-attack:#e6be5e;--hsbg-health:#d88179;--hsbg-cold:#a5c6e0;box-sizing:border-box;container:hsbg / inline-size;background:var(--surface-sunken);color:var(--text-primary);font:14px/1.45 var(--font-sans,system-ui,sans-serif);height:100%;min-height:420px;overflow:auto}
.hsbg-spectator *{box-sizing:border-box}.hsbg-spectator button,.hsbg-spectator input{font:inherit}.hsbg-spectator :focus-visible{outline:var(--focus-ring);outline-offset:var(--focus-ring-offset)}
.hsbg-toolbar{display:flex;align-items:center;gap:16px;padding:12px 20px;border-bottom:1px solid var(--border-faint);background:var(--surface)}
.hsbg-brand{font-weight:700;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}.hsbg-brand small{display:block;font-size:11px;letter-spacing:.16em;color:var(--text-muted);font-weight:400}
.hsbg-connection{display:flex;align-items:center;gap:8px;margin-left:auto;min-width:0}.hsbg-connection input{width:240px;max-width:30vw;min-height:36px;padding:8px 12px;background:var(--surface-sunken);border:1px solid var(--border);border-radius:4px;color:var(--text-primary)}
.hsbg-status{font-size:12px;color:var(--text-secondary);white-space:nowrap}.hsbg-error{padding:8px 20px;border-bottom:1px solid var(--border);color:var(--text-primary);background:var(--surface-raised)}
.hsbg-main{display:grid;grid-template-columns:minmax(0,1fr) 288px;min-height:620px}.hsbg-arena{min-width:0;display:flex;flex-direction:column;background:radial-gradient(ellipse at 50% 20%,var(--surface-raised),var(--surface-sunken) 75%)}
.hsbg-matchbar{display:flex;align-items:center;justify-content:space-between;padding:16px 24px 8px;gap:16px}.hsbg-phase{letter-spacing:.16em;text-transform:uppercase;font-size:12px;color:var(--accent)}.hsbg-matchbar h2{font-size:20px;margin:4px 0;font-weight:600}.hsbg-round{text-align:right;color:var(--text-muted)}.hsbg-round strong{display:block;color:var(--text-primary);font-size:18px}
.hsbg-board-scroll{overflow-x:auto;flex:1}.hsbg-board{position:relative;min-width:1000px;width:100%;height:560px;min-height:560px;isolation:isolate}.hsbg-board canvas{position:absolute;inset:0;width:100%;height:100%;display:block}.hsbg-board[data-fallback=true]{background:var(--surface-raised)}
.hsbg-row-label{position:absolute;left:50%;transform:translateX(-50%);text-align:center;pointer-events:none;z-index:2;white-space:nowrap;font-size:11px;text-transform:uppercase;letter-spacing:.2em;color:var(--text-secondary);padding:4px 12px;background:var(--surface-sunken);border:1px solid var(--border-faint);border-radius:3px}.hsbg-row-label--upper{top:12%}.hsbg-row-label--player{top:49%}
.hsbg-slot{position:absolute;transform:translate(-50%,-50%);width:90px;height:144px;z-index:3}.hsbg-token{position:relative;width:100%;height:100%;border:0;padding:0;background:transparent;color:var(--text-primary);cursor:pointer;border-radius:30%;text-align:center}.hsbg-token:hover .hsbg-token-name,.hsbg-token[aria-pressed=true] .hsbg-token-name{border-color:var(--accent);color:var(--accent)}.hsbg-tier{position:absolute;top:7px;left:50%;transform:translateX(-50%);font-size:11px;line-height:20px;min-width:26px;border:1px solid var(--border-strong);background:var(--surface-sunken);border-radius:10px;color:var(--accent)}
.hsbg-token-name{position:absolute;left:-4px;right:-4px;bottom:24px;height:34px;display:grid;place-items:center;font-size:12px;line-height:1.15;font-weight:650;padding:3px 4px;background:var(--surface-sunken);border:1px solid var(--border);border-radius:3px;text-wrap:balance}
.hsbg-token-stats{position:absolute;bottom:0;left:0;right:0;display:flex;justify-content:space-between;align-items:center;font-size:18px;font-weight:800;font-variant-numeric:tabular-nums}.hsbg-stat{min-width:30px;padding:0 5px;background:var(--surface-sunken);border:1px solid var(--border);border-radius:10px}.hsbg-stat--attack{color:var(--hsbg-attack)}.hsbg-stat--health{color:var(--hsbg-health)}.hsbg-token-abilities{font-size:11px;letter-spacing:.03em;color:var(--text-primary);padding:2px 3px;background:var(--surface-sunken);border-radius:3px}.hsbg-spell-cost{color:var(--accent);font-size:13px;width:100%;background:var(--surface-sunken);border:1px solid var(--border);border-radius:4px}.hsbg-slot-empty{position:absolute;left:0;right:0;top:42px;text-align:center;color:var(--text-muted);font-size:11px;pointer-events:none}.hsbg-slot-empty span{padding:4px 8px;background:var(--surface-sunken);border-radius:8px}
.hsbg-portrait{position:absolute;left:50%;top:50%;transform:translate(-50%,-53%);width:74%;height:54%;overflow:hidden;border-radius:50%;transition:transform .15s}.hsbg-portrait-image{width:100%;height:100%;object-fit:cover;transform:scale(1.36)}.hsbg-token:hover .hsbg-portrait,.hsbg-token:focus-visible .hsbg-portrait{transform:translate(-50%,-63%)}@media(prefers-reduced-motion:reduce){.hsbg-portrait{transition:none}}.hsbg-board-notice{position:absolute;left:24px;bottom:0;font-size:11px;color:var(--text-muted);margin:0;max-width:90%}
.hsbg-playerbar{display:flex;align-items:center;gap:24px;padding:12px 24px 20px;border-top:1px solid var(--border-faint);flex-wrap:wrap}.hsbg-player-name{margin-right:auto}.hsbg-player-name strong{display:block;font-size:16px}.hsbg-player-name small,.hsbg-player-stat small{display:block;color:var(--text-muted);font-size:11px;text-transform:uppercase;letter-spacing:.1em}.hsbg-player-stat strong{font-size:18px;font-variant-numeric:tabular-nums}.hsbg-player-stat--gold strong{color:var(--accent)}
.hsbg-advisor{border-left:1px solid var(--border-faint);padding:24px 20px;background:var(--surface);display:flex;flex-direction:column;gap:20px}.hsbg-advisor-heading{display:flex;justify-content:space-between;align-items:center}.hsbg-advisor-heading h2{font-size:18px;margin:0}.hsbg-advisor-heading small{font-size:10px;color:var(--text-muted);letter-spacing:.08em}.hsbg-advice-summary{display:flex;gap:16px;font-size:12px;color:var(--text-secondary)}.hsbg-advice-summary strong{display:block;font-size:20px;color:var(--accent)}.hsbg-actions{margin:0;padding:0;list-style:none;counter-reset:actions;display:grid;gap:16px}.hsbg-actions li{counter-increment:actions;display:grid;grid-template-columns:24px 1fr;gap:8px;line-height:1.55;color:var(--text-primary)}.hsbg-actions li:before{content:counter(actions);display:grid;place-items:center;width:24px;height:24px;border:1px solid var(--border-strong);border-radius:50%;color:var(--accent);font-size:12px}.hsbg-advice-note{color:var(--text-muted);font-size:12px;margin:0}.hsbg-runner{border-top:1px solid var(--border-faint);padding-top:16px}.hsbg-runner summary{cursor:pointer;color:var(--text-secondary);min-height:36px}.hsbg-runner ol{padding-left:20px;color:var(--text-muted);font-size:13px;display:grid;gap:8px}.hsbg-inspector{margin-top:auto;border-top:1px solid var(--border-faint);padding-top:16px}.hsbg-inspector h3{margin:0 0 8px;font-size:16px}.hsbg-inspector p{color:var(--text-secondary);margin:8px 0;font-size:13px}.hsbg-inspector small{color:var(--text-muted)}
.hsbg-empty-overlay{position:absolute;inset:25% 20% 35%;z-index:4;display:flex;align-items:center;justify-content:center;background:var(--surface-sunken);border:1px solid var(--border);border-radius:8px;padding:20px;text-align:center}.hsbg-offline-note{padding:0 24px 12px;margin:0;color:var(--text-muted);font-size:12px}
@container hsbg (max-width:1050px){.hsbg-main{grid-template-columns:minmax(0,1fr)}.hsbg-advisor{border-left:0;border-top:1px solid var(--border-faint);display:grid;grid-template-columns:1fr 1fr;gap:16px}.hsbg-advisor-heading,.hsbg-advice-summary,.hsbg-advice-note{grid-column:1/-1}.hsbg-inspector{margin-top:0}.hsbg-connection input{max-width:35vw}.hsbg-board{height:480px;min-height:480px}}
@container hsbg (max-width:600px){.hsbg-toolbar{flex-wrap:wrap;padding:12px}.hsbg-connection{width:100%;margin:0}.hsbg-connection input{max-width:none;flex:1;width:100px}.hsbg-status{margin-left:auto}.hsbg-advisor{display:flex}.hsbg-playerbar{gap:16px}.hsbg-player-name{width:100%}}
`;
