/**
 * The document-level JSON Schema for `.fabrika.jsonc`, assembled from the per-key fragments.
 *
 * Each key group carries its own `jsonSchema` fragment beside its `decode`, so the shape a repo
 * hand-edits is described in the one place its decoder already lives. This module joins the fifteen
 * fragments into one draft-07 document an editor validates the file against — a red squiggle on a
 * misspelled key or a wrong-typed value, where the only feedback used to be a decode failure at
 * runtime (#6488).
 *
 * **A registered key with no fragment refuses the assembly whole.** A schema missing one key's
 * properties would green a typo in that key's subtree, which is the silent gap this schema exists to
 * close; so an incomplete registry is named, never emitted over.
 */

import type {Registration} from "./key-group.ts";

/** The JSON Schema keywords the fragments use. Not the whole vocabulary — only what a fragment reaches for. */
export type JsonSchemaType =
	| "object"
	| "array"
	| "string"
	| "number"
	| "integer"
	| "boolean"
	| "null";

export interface JsonSchema {
	readonly type?: JsonSchemaType | ReadonlyArray<JsonSchemaType>;
	readonly description?: string;
	readonly enum?: ReadonlyArray<string>;
	readonly pattern?: string;
	readonly minLength?: number;
	readonly properties?: Readonly<Record<string, JsonSchema>>;
	readonly required?: ReadonlyArray<string>;
	readonly additionalProperties?: boolean | JsonSchema;
	readonly propertyNames?: JsonSchema;
	readonly items?: JsonSchema;
	readonly minItems?: number;
	readonly uniqueItems?: boolean;
}

/** The meta-schema the emitted document declares itself against — draft-07, which editors resolve. */
export const META_SCHEMA = "http://json-schema.org/draft-07/schema#";

/** The `$schema` pointer a repo writes into `.fabrika.jsonc` to bind it to the committed schema file. */
export const CONFIG_SCHEMA_FILE = ".fabrika.schema.json";

export interface ConfigSchemaDocument {
	readonly $schema: string;
	readonly title: string;
	readonly description: string;
	readonly type: "object";
	readonly properties: Readonly<Record<string, JsonSchema>>;
	readonly additionalProperties: false;
}

export type Assembly =
	/** Every registered key carried a fragment; this is the document to emit. */
	| {readonly _tag: "Complete"; readonly schema: ConfigSchemaDocument}
	/** One or more registered keys carry no fragment — the assembly is refused, naming them. */
	| {readonly _tag: "Incomplete"; readonly missing: ReadonlyArray<string>};

/**
 * The `$schema` self-pointer, admitted as a known property so `additionalProperties: false` does not
 * red the very line that binds the file to this schema.
 */
const SCHEMA_POINTER: JsonSchema = {
	type: "string",
	description: `Path to the JSON Schema for this file — e.g. "./${CONFIG_SCHEMA_FILE}". Gives an editor autocomplete and validation for the keys below.`,
};

/**
 * Assemble the document from the registry, in registry order.
 *
 * The completeness check is the invariant: a key added to the registry with no fragment refuses here
 * rather than shipping a schema that silently permits anything under its key. That is why the field
 * is optional on the type but required in practice — the assembler holds the rule a `?` cannot.
 */
export const assembleSchema = (registrations: ReadonlyArray<Registration>): Assembly => {
	const missing = registrations.filter((one) => one.jsonSchema === undefined).map((one) => one.key);
	if (missing.length > 0) return {_tag: "Incomplete", missing};

	const properties: Record<string, JsonSchema> = {$schema: SCHEMA_POINTER};
	for (const one of registrations) {
		if (one.jsonSchema !== undefined) properties[one.key] = one.jsonSchema;
	}

	return {
		_tag: "Complete",
		schema: {
			$schema: META_SCHEMA,
			title: "fabrika config (.fabrika.jsonc)",
			description:
				"Every key fabrika reads from .fabrika.jsonc. Each is independently optional and falls to its shipped default when absent; this schema documents the shape of a declared value. Generated by `fabrika config schema --write` — edit the key fragments in packages/fabrika-cli/src/config/keys/, never this file.",
			type: "object",
			properties,
			additionalProperties: false,
		},
	};
};

/** The committed schema serialized the way `--write` lands it — tab-indented, one trailing newline. */
export const serializeSchema = (schema: ConfigSchemaDocument): string =>
	`${JSON.stringify(schema, null, "\t")}\n`;

/**
 * Whether a committed schema document matches the assembled one, compared by content rather than
 * bytes: the file is re-formatted by the repo's own JSON formatter, so a whitespace difference is
 * not drift. Two documents agree when their compact serializations are equal.
 */
export const schemaMatches = (committed: unknown, assembled: ConfigSchemaDocument): boolean =>
	JSON.stringify(committed) === JSON.stringify(assembled);
