/**
 * The ocr-port filter spike — an exclusion set for the review reads, with its placement relative to
 * namespace derivation, and the hard refusal that keeps the filtering from blinding a guard.
 *
 * Local experimental spike for the ocr-port benchmark (`benchmarks/ocr-port/`), not part of the
 * review contract. The RFC fork it measures: excluding generated bytes BEFORE namespace derivation
 * (placement `before`) lets an all-excluded diff derive zero namespaces, while deriving first
 * (`after`) keeps the namespace rows over the full read and enumerates the excluded paths beside
 * them — a deliberate exclusion a reader can tell apart from a truncation.
 *
 * The refusal union is not declared here. `guard-trees.ts` composes the probe paths out of the
 * guards' own exported corpus constants and `.fabrika.jsonc`'s governed roots; this module only
 * knows how to refuse a pattern that matches a probe. A pattern is refused when it could match a
 * path a guard actually reads — probe-granular, not pattern-algebraic, because a universe-wide
 * suffix surface (leak-guard's `*.md`) would otherwise intersect every directory exclusion and
 * refuse the spike's own defaults.
 */
import {type ClassName, classOf, type Partition, partition} from "./classes.ts";

/** One exclusion pattern, with where it came from — a default, a config key, or the caller's `--exclude`. */
export interface ExclusionPattern {
	readonly pattern: string;
	readonly source: "default" | "config" | "caller";
}

/**
 * The default exclusion set: the lockfile, snapshot directories, and the generated-schema and
 * build-output shapes this repo's `.gitignore` `# Generated` block already names.
 */
export const DEFAULT_EXCLUSIONS: ReadonlyArray<ExclusionPattern> = [
	{pattern: "pnpm-lock.yaml", source: "default"},
	{pattern: "**/__snapshots__/**", source: "default"},
	{pattern: "**/__generated__/**", source: "default"},
	{pattern: "**/schema.graphql.generated", source: "default"},
	{pattern: "**/__mutation__/**", source: "default"},
];

/** The two RFC placements. `null` (the flag omitted) means no filtering at all. */
export type FilterPlacement = "before" | "after";

export const isFilterPlacement = (value: string): value is FilterPlacement =>
	value === "before" || value === "after";

/**
 * One guard probe: a path the named guard actually reads, composed from that guard's own exported
 * constants in `guard-trees.ts`. A pattern matching any probe is refused.
 */
export interface GuardProbe {
	readonly guard: string;
	readonly path: string;
	/** The guard source file the probe was composed from — what the sync golden test re-reads. */
	readonly source: string;
}

const escapeRegex = (segment: string): string => segment.replace(/[.+^${}()|[\]\\]/g, "\\$&");

/**
 * The pattern to a full-match regex. Slash-separated: `*` is anything but a slash inside one
 * segment; a double-star segment spans any number of directories including none — a leading
 * double-star prefix lets the next segment match at the root as well as at any depth, and a
 * trailing double-star (or a trailing slash) matches everything under the prefix; anything else is
 * literal.
 */
export const patternToMatcher = (pattern: string): RegExp => {
	const trimmed = pattern.replace(/\/+$/, "");
	const under = trimmed !== pattern;
	const parts = trimmed.split("/").filter((part) => part !== "");
	let source = "^";
	let needSlash = false;
	for (const [index, part] of parts.entries()) {
		const last = index === parts.length - 1;
		if (part === "**") {
			if (last) {
				source += `${needSlash ? "/" : ""}.*`;
				needSlash = false;
			} else {
				source += `${needSlash ? "/" : ""}(?:[^/]+/)*`;
				needSlash = false;
			}
			continue;
		}
		const segment = part.includes("*")
			? escapeRegex(part).replace(/\*/g, "[^/]*")
			: escapeRegex(part);
		source += `${needSlash ? "/" : ""}${segment}`;
		needSlash = true;
	}
	if (under) source += "(?:/.*)?";
	return new RegExp(`${source}$`);
};

export const matchPath = (pattern: string, path: string): boolean =>
	patternToMatcher(pattern).test(path);

/** `--exclude` arrives as a comma-separated list; blanks are dropped, never treated as a pattern. */
export const parseExcludeList = (csv: string): ReadonlyArray<ExclusionPattern> =>
	csv
		.split(",")
		.map((entry) => entry.trim())
		.filter((entry) => entry !== "")
		.map((pattern) => ({pattern, source: "caller" as const}));

/**
 * The defaults the effective set dropped: every default whose pattern string no entry of the set
 * carries. A default removed and re-added by the same pattern string is back in the set — the
 * re-addition is the later, more specific declaration — so it does not appear here; the
 * enumeration must never name a default the filter still applies.
 */
export const unexcludedDefaults = (
	patterns: ReadonlyArray<ExclusionPattern>,
): ReadonlyArray<string> =>
	DEFAULT_EXCLUSIONS.map(({pattern}) => pattern).filter(
		(pattern) => !patterns.some((entry) => entry.pattern === pattern),
	);

/** The assembled exclusion set: the patterns a run filters over, and the defaults it dropped. */
export interface EffectiveExclusions {
	readonly patterns: ReadonlyArray<ExclusionPattern>;
	/** The removed defaults nothing re-added — enumerated, so a removal is never silent. */
	readonly unexcluded: ReadonlyArray<string>;
}

/**
 * The effective exclusion set: `(DEFAULT_EXCLUSIONS − removals) + config additions + CLI`, with one
 * entry per pattern string and a deterministic order — defaults in declaration order, then config
 * additions in declaration order, then the CLI's.
 *
 * A later declaration equal in string to an earlier entry is a duplicate, not an override; a
 * duplicate that re-adds a removed default is exactly what lifts that default out of
 * `unexcluded`. The refusal union of every filtering consumer runs over this set, so a config
 * addition is refused on a guard-probe match exactly as a default or a CLI flag is.
 */
export const effectiveExclusions = (
	configAdditions: ReadonlyArray<string>,
	configRemovals: ReadonlyArray<string>,
	cliExclude: string | null,
): EffectiveExclusions => {
	const removed = new Set(configRemovals);
	const patterns: ExclusionPattern[] = [];
	const add = (pattern: string, source: ExclusionPattern["source"]): void => {
		if (patterns.some((entry) => entry.pattern === pattern)) return;
		patterns.push({pattern, source});
	};
	for (const {pattern} of DEFAULT_EXCLUSIONS) {
		if (!removed.has(pattern)) add(pattern, "default");
	}
	for (const pattern of configAdditions) add(pattern, "config");
	if (cliExclude !== null) {
		for (const {pattern} of parseExcludeList(cliExclude)) add(pattern, "caller");
	}
	return {patterns, unexcluded: unexcludedDefaults(patterns)};
};

/**
 * A pattern refused because it matches a guard probe. `guard` names the guard whose probe matched;
 * a user pattern is corrected, a default matching a probe is a spike bug and refuses all the same.
 */
export interface FilterRefusal {
	readonly pattern: string;
	readonly guard: string;
	readonly probe: string;
}

export const refusalFor = (
	patterns: ReadonlyArray<ExclusionPattern>,
	probes: ReadonlyArray<GuardProbe>,
): ReadonlyArray<FilterRefusal> => {
	const refusals: FilterRefusal[] = [];
	for (const {pattern} of patterns) {
		const probe = probes.find((candidate) => matchPath(pattern, candidate.path));
		if (probe !== undefined) {
			refusals.push({pattern, guard: probe.guard, probe: probe.path});
		}
	}
	return refusals;
};

/** The split one placement applies: the kept paths and the excluded ones, input order preserved. */
export interface PathSplit {
	readonly kept: ReadonlyArray<string>;
	readonly excluded: ReadonlyArray<string>;
}

export const applyPlacement = (
	files: ReadonlyArray<string>,
	patterns: ReadonlyArray<ExclusionPattern>,
): PathSplit => {
	const kept: string[] = [];
	const excluded: string[] = [];
	for (const file of files) {
		(patterns.some(({pattern}) => matchPath(pattern, file)) ? excluded : kept).push(file);
	}
	return {kept, excluded};
};

/** One `diff --git` section, kept whole so a filtered diff stays a well-formed unified diff. */
export interface DiffSection {
	readonly path: string;
	readonly text: string;
}

/**
 * The diff's per-file sections. The path is read off the `diff --git a/… b/…` header unquoted —
 * git quotes non-ASCII and special-character paths, and the spike's benchmark diffs are plain
 * ASCII, so a quoted header is out of the spike's stated bound (`../review/diff.ts` handles the
 * quoted forms for the count proof).
 */
export const diffSections = (diff: string): ReadonlyArray<DiffSection> => {
	const sections: DiffSection[] = [];
	// CRLF-tolerant: diffs checked out with autocrlf (or authored on Windows) carry \r that would
	// otherwise glue itself onto every parsed header and path.
	const lines = diff.split("\n").map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
	let current: string[] | null = null;
	let path: string | null = null;
	const flush = (): void => {
		if (current !== null && path !== null) {
			sections.push({path, text: current.join("\n")});
		}
	};
	for (const line of lines) {
		const header = /^diff --git a\/(.+) b\/(.+)$/.exec(line);
		if (header !== null) {
			flush();
			current = [line];
			path = header[2] ?? header[1] ?? null;
		} else if (current !== null) {
			current.push(line);
		}
	}
	flush();
	return sections;
};

/**
 * The filtered diff: the machine-readable exclusion header, then the kept sections whole. The
 * header is what tells a deliberate exclusion apart from a truncation — the diff verbs' own
 * completeness proof runs on the UNFILTERED bytes and stays untouched by this module.
 *
 * `unexcluded` names the removed defaults the set carried, appended sorted after the excluded
 * paths so a config removal is stated in the same header a caller already reads. Empty is the
 * shipped shape: no removal, no lines, bytes identical to a run without the config keys.
 */
export const filterDiff = (
	diff: string,
	excluded: ReadonlyArray<string>,
	placement: FilterPlacement,
	unexcluded: ReadonlyArray<string> = [],
): string => {
	const excludedSet = new Set(excluded);
	const served = diffSections(diff).filter((section) => !excludedSet.has(section.path));
	const header = [
		`x-fabrika-filter: placement=${placement} excluded=${excluded.length} served=${served.length}`,
		...[...excluded].sort().map((path) => `x-fabrika-excluded-path: ${path}`),
		...(unexcluded.length > 0
			? [...unexcluded].sort().map((path) => `x-fabrika-unexcluded-path: ${path}`)
			: []),
	];
	return [...header, "", ...served.map((section) => section.text)].join("\n");
};

export interface PreviewResult {
	readonly placement: FilterPlacement;
	/** The paths that survive the filter — the ones a reviewer would read. */
	readonly matched_paths: ReadonlyArray<string>;
	readonly excluded: ReadonlyArray<string>;
	/** The removed defaults the set still lacks — carried so every emission enumerates the same list. */
	readonly unexcluded: ReadonlyArray<string>;
	readonly active_classes: Partition["classes"];
	readonly namespaces: ReadonlyArray<string>;
	readonly filtered_diff: string;
	readonly filtered_diff_bytes: number;
	readonly filtered_diff_lines: number;
}

export type Preview =
	| {_tag: "Refused"; refusals: ReadonlyArray<FilterRefusal>}
	| {_tag: "Preview"; result: PreviewResult};

/**
 * The preview derivation, end to end, with no LLM and no network: split the diff's paths by the
 * exclusion set, derive the class partition at the requested placement, and filter the diff bytes.
 *
 * The set is an {@link effectiveExclusions} product, so the removed defaults it still lacks are
 * derived off the patterns themselves — a default is absent from an effective set exactly when it
 * was removed and nothing re-added it — and carried onto the result and into the filtered diff's
 * header.
 *
 * `before` partitions the KEPT paths only — an all-excluded diff derives zero classes and zero
 * namespaces. `after` partitions the FULL read — the namespace rows stand unchanged and the
 * excluded paths are enumerated beside them.
 */
export const previewOf = (
	diff: string,
	placement: FilterPlacement,
	patterns: ReadonlyArray<ExclusionPattern>,
	probes: ReadonlyArray<GuardProbe>,
): Preview => {
	const refusals = refusalFor(patterns, probes);
	if (refusals.length > 0) return {_tag: "Refused", refusals};
	const unexcluded = unexcludedDefaults(patterns);
	const sections = diffSections(diff);
	const paths = sections.map((section) => section.path);
	const split = applyPlacement(paths, patterns);
	const partitionSource = placement === "before" ? split.kept : paths;
	const partitioned = partition(partitionSource);
	const filtered = filterDiff(diff, split.excluded, placement, unexcluded);
	return {
		_tag: "Preview",
		result: {
			placement,
			matched_paths: split.kept,
			excluded: split.excluded,
			unexcluded,
			active_classes: partitioned.classes,
			namespaces: partitioned.classes.map((entry) => `review-${entry.name as ClassName}`),
			filtered_diff: filtered,
			filtered_diff_bytes: Buffer.byteLength(filtered, "utf8"),
			filtered_diff_lines: filtered.split("\n").length,
		},
	};
};

/** The one class a path belongs to — re-exported so the CLI test asserts through the same map. */
export const classOfClass = classOf;
