export {DuplicateSpellPath, SpellNotFound} from "./errors.ts";
export {
	buildSpellIndex,
	type Candidate,
	type CandidateKind,
	complete,
	describeExpected,
	didYouMean,
	type IndexedSpell,
	type IndexNode,
	type ParamSpec,
	type ParseResult,
	parse,
	readParams,
	type SpellCallDraft,
	type SpellIndex,
	type Token,
	type Tokenization,
	tokenize,
} from "./parse/index.ts";
export {
	buildRegistry,
	describeSource,
	describeSpell,
	type RegistryTable,
	type SpellDescription,
	type SpellNode,
	SpellRegistry,
	type SpellRow,
	type SpellSource,
} from "./registry.ts";
export {
	type AnySpell,
	ClientId,
	defineSpell,
	renderPath,
	type Scope,
	type Spell,
	type SpellPath,
	WindowId,
	WorkspaceId,
} from "./spell.ts";
